name: CI/CD Pipeline for User API With Keploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install Go dependencies
        working-directory: ./backend
        run: go mod tidy

      - name: Build the project
        working-directory: ./backend
        run: go build ./...

      - name: Setup Keploy CLI
        run: |
          curl --silent -L https://keploy.io/ent/install.sh | bash

      - name: Run Keploy Test Suite
        run: |
          export KEPLOY_API_KEY=${{ secrets.KEPLOY_API_KEY }}
          keploy test-suite --app=<your-app-id> --base-path http://localhost:8080 --cloud
